# Generated by Django 3.0.5 on 2020-11-13 05:28

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='profile/default.png', upload_to=authentication.models.upload_to),
        ),
    ]
